### ISSUE TITLE
Feature Request: [Option to?] Retain Python Logger Names

### ISSUE THREAD

**Issue by NfNitLoop** [dylanbstorey/pyo3-pylogger#4]
# Context #

I'm calling into a large-ish Python codebase from Rust.  It consists of multiple packages, each of which uses a named Python logger for logs.

In Python, it's easy to see which logs come from which (named) logger, but in Rust, it appears that the name of the logger is [ignored][1]. So, if I init logging like this:

```rust
pyo3_pylogger::register("python");
```

All of the logs, from all of the various Python packages, end up with the same "python" prefix, and lose their individual contexts.

[1]: https://github.com/dylanbstorey/pyo3-pylogger/blob/2a9e9ed47e4ab3f73e43fc4d912eff895873ef07/src/lib.rs#L25

# Request #

Please include the python logger name in the output!  IMO it should be present by default, but if you don't want to break backward compatibility, I suppose it could be opt-in.

---
Thanks for this library!  😊

**Comment by NfNitLoop** [comment]
This branch is working for me!  

https://github.com/dylanbstorey/pyo3-pylogger/compare/main..NfNitLoop:pyo3-pylogger:with-logger-name

**Comment by dylanbstorey** [comment]
Will merge and release this evening.  Thanks for contributing !

**Comment by dylanbstorey** [comment]
0.2.2 released, thanks for the PR
